### ISSUE TITLE
emacs-version still reports 26.1.92 in 26.2

### ISSUE THREAD

**Issue by debajit** [railwaycat/homebrew-emacsmacport#168] opened 2019-04-15 22:15 UTC
I upgraded to the latest release of emacs-mac, and when I run a C-h n, I can see the documentation updated for 26.2. 

However when I run a M-x emacs-version, it reports 26.1.92. 

These values are not in agreement. They should be.

**Comment by railwaycat** [comment] 2019-04-16 00:09
Hi, can I have more info about how you install emacs-mac? By brew or brew cask?

**Comment by debajit** [comment] 2019-04-16 20:41
I upgraded using `brew cask reinstall emacs-mac`

**Comment by railwaycat** [comment] 2022-09-17 17:13
I will close this issue for now since there has several major versions since the issue was created. I can see on the latest 28.2-mac-9.1 this issue is not reproducible. Please feel free to reopen it or open new one if same issue occurs.

**Closed by railwaycat** 2022-09-17 17:13 UTC
