### ISSUE TITLE
Crash on return from screen lock

### ISSUE THREAD

**Issue by dschien** [railwaycat/homebrew-emacsmacport#20] opened 2015-04-01 16:40 UTC
Hi,

I'm using binary emacs-24.5-rc1-mac-5.6.
Emacs crashes when I return from the lock screen

Steps to reproduce:
1. start emacs
2. enter screen lock (option+cmd+power)
3. touch any key to unlock

Result:
Emacs crashes

I'm sure that is particular to my machine otherwise others would have issued this already but I'm hoping to get ideas how to debug this.

Many thanks,
Dan

**Comment by dschien** [comment] 2015-04-02 10:34
By the way, emacs does not crash if I put the machine to sleep by closing the lid.

**Comment by railwaycat** [comment] 2020-05-20 18:24
Sorry, I will close it for now since I'm not able to reproduce this problem on the latest version. Please feel free to reopen it or open a new issue if you see this problem again. Thanks!

**Closed by railwaycat** 2020-05-20 18:24 UTC
