### ISSUE TITLE
Causing brew upgrade failure

### ISSUE THREAD

**Issue by raguay** [railwaycat/homebrew-emacsmacport#71] opened 2016-07-30 13:14 UTC
When I execute brew upgrade -v, I get this output:

Warning: Calling 'depends_on :autoconf' is deprecated!
Use 'depends_on "autoconf" => :build' instead.
/usr/local/Library/Taps/railwaycat/homebrew-emacsmacport/Formula/emacs-mac.rb:10:in `<class:EmacsMac>'

Warning: Calling 'depends_on :automake' is deprecated!
Use 'depends_on "automake" => :build' instead.
/usr/local/Library/Taps/railwaycat/homebrew-emacsmacport/Formula/emacs-mac.rb:11:in `<class:EmacsMac>'

This is stopping the upgrade process and messing up my BitBar script.

Mac OS X 10.11.6 (15G31)

It just started happening after the last emacs update.

**Comment by railwaycat** [comment] 2016-07-30 16:34
Hi @raguay, thanks for the report! I'll close this one since it's a duplicate of #70

**Closed by railwaycat** 2016-07-30 16:34 UTC
