### ISSUE TITLE
emacs freeze apple m1

### ISSUE THREAD

**Issue by yanglimingcn** [railwaycat/homebrew-emacsmacport#260] opened 2021-07-30 14:42 UTC
emacs will freeze when I invoke Mac dictionary by typing 'Ctrl-Super-d'
GNU Emacs 27.2 (build 1, arm-apple-darwin20.3.0, Carbon Version 164 AppKit 2022.3) of 2021-03-28

**Comment by yanglimingcn** [comment] 2021-08-04 07:36
brew install emacs-mac is ok
brew install --cask emacs-mac will case freeze

**Comment by railwaycat** [comment] 2021-09-12 21:02
I tried to reproduce but failed. Could you confirm this issue exists if you start with `/Applications/Emacs.app/Contents/MacOS/Emacs -q`?

Also if you can provide the version of your macOS that will be great!

**Comment by bebound** [comment] 2021-12-19 02:50
I met the same issue on my new M1 Pro MacBook.

I tried to install `emacsmacport` by brew and cask. Both mothods lead to same wired result.
I use spacemacs. In spaceamacs home buffer, everything works like a charm. After open file, the vim mode is invalid, and when type `<space> <space>`, the emacs will minimize to dock. Type `ctrl-z`, the app freeze, I can see the mode line color keep changing (seem it try to switch from two different vim mode).

I failed to fix these issues. Then I installed Emacs from https://emacsformacosx.com.  This app works. And magically, all of the wired issue also disappears in `emacsmacport`.

**Comment by railwaycat** [comment] 2022-04-05 16:51
I'm not sure if this is because of my M1 Big Sur CI setup. 

I'm considering moving the CI setup from Big Sur to Monterey since Monterey supports running macOS VM on M1. A clean and modern build setup could avoid lots of mystery issues. However in that case, the cask for M1 will be Monterey (and newer) only. I guess there is very less M1 users stick with Big Sur at this time?

**Comment by railwaycat** [comment] 2022-04-10 00:39
The latest 28.1-mac-9.0 cask includes builds on macOS 12 Monterey. Could you have a try to see if the issue still exists?

**Comment by railwaycat** [comment] 2022-09-17 17:53
I will close this issue for now and please feel free to reopen it or open new one if same issue occurs.

**Closed by railwaycat** 2022-09-17 17:53 UTC

**Comment by BrownShibaDog** [comment] 2022-09-25 07:27
> brew install emacs-mac is ok
> brew install --cask emacs-mac will case freeze

Just FYI, I had same problem on my Apple M1.
But if I start Emacs by `/Applications/Emacs.app/Contents/MacOS/Emacs.sh -Q`, the problem won't happen.
And after testing `Emacs.sh -Q`, I cannot reproduce the freeze anymore.

However, I have another problem on cask emacs-mac ( #223 ), I'm using formula emacs-mac.
